#!/bin/bash
#
#
envName=K8S-${LOGNAME}
envType="K8S"
repoName=$1
yourEnvDescription="K8s $yourEnvName from $KOSLI_OWNER at Repo $repoName with Owner $KOSLI_OWNER"
# --template artifact,evidence-type1,evidence-type2 \
templateName=evidence-type1

kosli environment declare  --environment-name  $envName \
	--environment-type $envType \
	--description $yourEnvDescription \
	--api-token $KOSLI_API_TOKEN \
	--owner $KOSLI_OWNER 


